CREATE DATABASE CITYINFO;

USE CITYINFO;

CREATE TABLE CITY (

ID          INT,
STATE       VARCHAR(50),
COUNTRYCODE VARCHAR(50),
DISTRICT    VARCHAR(50),
POPULATION  VARCHAR(50),

DESCRIBE    CITY;




SELECT * FROM CITY WHERE POPULATION > '100000' AND COUNTRYCODE = 'USA';

SELECT DISTINCT CITY FROM STATION WHERE LOWER(CITY) LIKE 'a%' OR LOWER(CITY) LIKE 'e%' OR LOWER(CITY) LIKE 'i%' OR LOWER(CITY) LIKE 'o%' OR LOWER(CITY) LIKE 'u%';

SELECT DISTINCT CITY FROM STATION WHERE RIGHT(CITY, 1) IN ('a', 'e', 'i', 'o', 'u');
