CREATE DATABASE CITYINFO;

USE CITYINFO;

CREATE TABLE CITY (

ID INT,
STATE VARCHAR(50),
COUNTRYCODE VARCHAR(50),
DISTRICT VARCHAR(50),
POPULATION VARCHAR(50),

DESCRIBE books;


SELECT * FROM CITY WHERE POPULATION > '100000' AND COUNTRYCODE = 'USA';