/* Hackrank */

/* 

SELECT * FROM CITY WHERE POPULATION > '100000' AND COUNTRYCODE = 'USA';

SELECT DISTINCT CITY FROM STATION WHERE LOWER(CITY) LIKE 'a%' OR LOWER(CITY) LIKE 'e%' OR LOWER(CITY) LIKE 'i%' OR LOWER(CITY) LIKE 'o%' OR LOWER(CITY) LIKE 'u%';

SELECT DISTINCT CITY FROM STATION WHERE LEFT(CITY,1) IN ('a','e','i','o','u') AND RIGHT(CITY,1) IN ('a','e','i','o','u');

SELECT Name FROM STUDENTS WHERE Marks > '75' ORDER BY RIGHT(Name,3), ID ASC;

SELECT name FROM Employee ORDER BY name ASC;

SELECT name FROM Employee WHERE salary > '2000' AND months < '10';

SELECT DISTINCT CITY FROM STATION WHERE RIGHT(CITY,1) NOT IN ('a','e','i','o','u');

SELECT DISTINCT CITY FROM STATION WHERE LEFT(CITY,1) NOT IN ('a','e','i','o','u');

SELECT DISTINCT CITY FROM STATION WHERE LEFT(CITY,1) NOT IN ('a','e','i','o','u') OR RIGHT(CITY,1) NOT IN ('a','e','i','o','u');

*/

