USE COMPANY;

/* CREATE TABLE BODHIBENCH( ID INT, SHAPE INT, MATERIAL VARCHAR(50), DIMENSIONS VARCHAR(50), COLOR VARCHAR(50), CLIENTNAME VARCHAR(50), CLIENTLOCATION VARCHAR(50)); */

/* CREATE TABLE EMPLOYEES( EMPID INT, EMPNAME VARCHAR(50), EMPSALARY INT, EMPAGE INT, EMPCITY VARCHAR(50) ); */

/* DESCRIBE BODHIBENCH; */

/* DESCRIBE EMPLOYEES; */

/* SELECT EMPID, EMPNAME, EMPSALARY, EMPAGE, EMPCITY, EMPSTATE FROM EMPLOYEES; */

/* SELECT * FROM EMPLOYEES; */ 

/* INSERT INTO EMPLOYEES (EMPID, EMPNAME, EMPSALARY, EMPAGE, EMPCITY, EMPSTATE )

VALUES    ( '1', 'John Michael Garofalo', '160000', '38', 'Tucson', 'AZ' ); */

/* SET SQL_SAFE_UPDATES = 0;

/* DELETE FROM EMPLOYEES WHERE EMPID = '1'; */

/*UPDATE EMPLOYEES SET EMPNAME = 'John Michael Garofalo' WHERE EMPID = '1'; 

SET SQL_SAFE_UPDATES = 1; */

/* INSERT INTO EMPLOYEES (EMPID, EMPNAME, EMPSALARY, EMPAGE, EMPCITY, EMPSTATE)
VALUES ('2', 'Deanna Marie Esparza', '120000', '28', 'Tucson', 'AZ' ); */

/* SELECT * FROM EMPLOYEES;*/

/* SELECT * FROM EMPLOYEES WHERE EMPNAME LIKE 'J%o'; */

/* SELECT * FROM EMPLOYEES WHERE EMPNAME LIKE 'D%a'; */