/* CREATE DATABASE CITYINFO;

USE CITYINFO;

CREATE TABLE CITY (

ID          INT(15)
STATE       VARCHAR(50),
COUNTRYCODE VARCHAR(50),
DISTRICT    VARCHAR(50),
POPULATION  VARCHAR(50) ) 

*/

/* DESCRIBE CITY; */

/* ALTER TABLE CITY
CHANGE COLUMN ID ID INT AUTO_INCREMENT PRIMARY KEY,
CHANGE COLUMN STATE STATE_ID INT,
ADD COLUMN DESCRIPTION TEXT,
ADD COLUMN PARTY ENUM('DEMOCRAT','REPUBLICAN','INDEPENDENT'),
ADD COLUMN REPRESENTATIVE_ID INT,
ADD COLUMN ELECTION_YEAR VARCHAR(4),
ADD COLUMN SS_NUMBER VARCHAR(20);
*/

/* DESCRIBE CITY; */










